### PR TITLE
Convert property values to string

### PR DESCRIPTION
**Pull request by Beakerboy**

### CODE REVIEW

**Comment by Beakerboy** [comment]
I modified a test file to include an int valued property key. Running the test on the current master will fail, but will pass on this pull request.

**Comment by Beakerboy** [comment]
This pull request addresses #4

**Review by kshitijrajsharma — APPROVED** [review]
Awesome 👏

**Comment by kshitijrajsharma** [comment]
> This pull request addresses #4 

Worthwhile to use github convention on the description like following 
- Resolve #4 
While doing so , merging PR will automatically close the issue

**Pull request merged**
